language: node_js
node_js:
    - "node"
sudo: required

services:
- docker

script:
- npm test

after_success:
- heroku container:login
- heroku container:push web -a $HEROKU_APP_NAME
- heroku container:release web -a $HEROKU_APP_NAME
