version: '3'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/backend
    ports: 
      - "3000:3000"
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/frontend
    ports:
      - "8080:8080"  
    environment:
      - CHOKIDAR_USEPOLLING=true